name: skdv
description: Projeto de aplicativo de e-commerce para cuidados com a pele, desenvolvido com Flutter e integrado com AWS.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Adiciona fontes Google
  google_fonts: ^2.1.0

  # Ícones estilo iOS
  cupertino_icons: ^1.0.8

  # Dependências para o desenvolvimento
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/KITR.webp
    - assets/LOCAO_RAINHA2.webp
    - assets/LOCAO_RAINHA.webp
    - assets/LOCAO_RAINHA3.webp
    - assets/MaSCARARAINHA2.webp
    - assets/MaSCARARAINHA3.webp
    - assets/MASCARARAINHA.webp
    - assets/POCAO_RAINHA_DIURNA.webp
    - assets/POCAO_RAINHA_DIURNA2.webp
    - assets/POCAO_RAINHA_NOTURNA.webp
    - assets/POCAO_RAINHA_NOTURNA2.webp
    - assets/SABONETE_FACIAL_RAINHA.webp
    - assets/SABONETE_FACIAL_RAINHA2.webp
    - assets/SABONETE_FACIAL_RAINHA3.webp

