name: skdv
description: Um projeto Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  # Outras dependências

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
 #   - assets/kit_rainha_revolution.webp
 #   - assets/locao_rainha2.webp
 #   - assets/locao_rainha.webp
 #   - assets/locao_rainha3.webp
 #   - assets/mascara_rainha_2.webp
 #   - assets/mascararainha3.webp
 #   - assets/mascararainha.webp
 #   - assets/pocao_rainha_diurna.webp
 #   - assets/pocao_rainha_diurna2.webp
 #   - assets/pocao_rainha_noturna.webp
 #   - assets/pocao_rainha_noturna2.webp
 #   - assets/sabonete_facial_rainha.webp
 #   - assets/sabonete_facial_rainha2.webp
 #   - assets/sabonete_facial_rainha3.webp
